# Generated by Django 5.0.1 on 2024-01-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Tags',
        ),
    ]
