# Generated by Django 5.0.1 on 2024-01-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_category_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='pin',
            old_name='category',
            new_name='tags',
        ),
    ]
