# Generated by Django 5.0.1 on 2024-01-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_tags_tag_rename_category_pin_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='tags',
        ),
        migrations.AddField(
            model_name='pin',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='base.tag'),
        ),
    ]
