# Generated by Django 5.0.1 on 2024-02-21 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_pin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pin',
            name='picture',
            field=models.ImageField(default='avatar.svg', upload_to='user-pins/'),
        ),
        migrations.RemoveField(
            model_name='pin',
            name='tags',
        ),
        migrations.AddField(
            model_name='pin',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='base.tag'),
        ),
    ]
