# Generated by Django 5.0.1 on 2024-02-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_pin_name_alter_pin_picture_remove_pin_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='picture',
            field=models.ImageField(default='avatar.svg', upload_to=''),
        ),
    ]
